version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: tourmeg-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Depending on how the OSM file is loaded, it seems to be bundled in the jar or mapped via resources

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tourmeg-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
