# Step 1: Build the app
FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app
# Docker cache for dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Step 2: Run the app
# Using 'jre' instead of 'jdk' makes the final image significantly smaller
FROM eclipse-temurin:25-jre 

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
